### ISSUE TITLE
Add "docker" instructions for running neo4j to wiki

### ISSUE THREAD

**Issue by slackr** [BloodHoundAD/BloodHound#184]
I've had success quickly deploying neo4j for Bloodhound using docker. It may be useful to add this to the Wiki:

`docker run -p 7474:7474 -p 7687:7687 neo4j `

**Comment by RamblingCookieMonster** [comment]
Hiyo!

A few quick thoughts!

* I'd suggest mapping volumes for both data and logs as @lostInSpaceSomewhere mentioned
* At least mention that 7473 for https, maybe publish it?
* An actual start-to-working-example bit.  Not just 'here's how to run docker'
* Again, like @lostInSpaceSomewhere alluded to... it might be fun to see a docker image that includes both Neo4j and Bloodhound : )

Cheers!

**Comment by slackr** [comment]
@lostInSpaceSomewhere the docker image contains only neo4j and by default wont persist. I've found it useful for quick deployments of BH

**Comment by lostInSpaceSomewhere** [comment]
im curious on the docker build
i have tried the following command with no success:
``` docker run -p 7474:7474 -p 7687:7687 specterops/bloodhound-neo4j -v ./logs:/var/lib/neo4j/logs -v ./db:/var/lib/neo4j/data/databases ```
__error:__ ``` /docker-entrypoint.sh: line 17: exec: -v: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...] ```

created two seperate volume via ``` docker volume create bhLogs ``` and ``` docker volume create bhDatabases ```
ran: ```docker run -p 7474:7474 -p 7687:7687 specterops/bloodhound-neo4j -volumes bhDatabases:/var/lib/neo4j/data/databases ```
also tried: ```docker run -p 7474:7474 -p 7687:7687 specterops/bloodhound-neo4j -m bhDatabases:/var/lib/neo4j/data/databases```

all had the same errors

i also tried a docker-compose file
```
version: '3'
services:
    neo4j:
        image: specterops/bloodhound-neo4j
    volumes:
        - logs:/var/lib/neo4j/logs:rw
        - databases:/var/lib/neo4j/data/databases:rw
    ports:
        - 7474:7474
        - 7687:7687
volumes:
    logs:
    databases:
```
__error:__``` ERROR: In file '.\docker-compose.yml', service 'volumes' must be a mapping not an array. ```

im no expert in docker or compose, although have used them for a few different projects, so not sure where the issue is
-- if you have any thoughts let me know

**Comment by lostInSpaceSomewhere** [comment]
Fixed the compose file...not sure why wouldnt run in the standard docker run command

compose file:
```
version: '3'
services:
    neo4j:
        image: specterops/bloodhound-neo4j
        volumes:
            - ./logs:/var/lib/neo4j/logs
            - ./databases:/var/lib/neo4j/data/databases
        ports:
            - 7474:7474
            - 7687:7687

```

_maybe its useful to someone_
